### ISSUE TITLE
Did you think I wouldn't find out?

### ISSUE THREAD

**Issue by stutteringp0et** [ximware/plg_sys_offlive#1]
This is an almost verbatim copy (ripoff) of my Offline plugin.  Joomla allows forks, but they REQUIRE attribution.

I wouldn't be upset, except that you're claiming it as your own code - which it is not.  And that makes you a plagiarist.

I'm making sure you're famous - You're named on my website as a plagiarist.  I've got over a half million downloads, so people are definitely going to see it.

**Comment by stutteringp0et** [comment]
Looks like you didn't even write the very minor change you made - IP whitelist.  The IP address collection was written by Sivanesh Govindan here:

http://stackoverflow.com/questions/15699101/get-the-client-ip-address-using-php/19189952

I'm quite familiar with that code, because I didn't like it and wrote my own solution to the question.  It can be seen right below Sivanesh's answer on the same stackoverflow page.

**Comment by alebak** [comment]
@stutteringp0et Blah, blah!

Where is the Offline plugin repository? When was the last support of the Offline plugin?

If so much it annoys then don't use Offlive plugin. I modified Offline plugin by a need of mine and I wanted it to share, and I go to add it new features. Some problem?

Is Ubuntu a copy (or plagiarism) of Debian?

Please, ripen, cry less and coding more.

**Comment by stutteringp0et** [comment]
You removed my copyright notice, you've removed all indication that you didn't write it.  This is copyright infringement.

Yes, I use Linux - but I never claimed that I wrote it.

You have stolen my code and now admitted to doing it.  Thanks for the screenshot.

**Comment by stutteringp0et** [comment]
My extension has been published in the JED since 2014.  There isn't any way to contest about who released first.

If you had left attribution, I wouldn't have said a word.  But you claimed to write it, and that makes you a thief.

**Comment by stutteringp0et** [comment]
Just in case you try to edit your admission of guilt

![image](https://cloud.githubusercontent.com/assets/310899/16127548/939b6d12-33c2-11e6-82c2-ce3db058935d.png)

**Comment by alebak** [comment]
@stutteringp0et Hahaha!

A code public from http://stackoverflow.com/ and a general solution?

Please, find something to do instead of mourn. I hope your demand. I will return rich man with this plugin.

Do you have 13 years old? Right?

**Comment by stutteringp0et** [comment]
In case you didn't read the JED rules, you MUST provide attribution when creating a fork.

https://docs.joomla.org/Forked_Extensions
http://extensions.joomla.org/support/knowledgebase/item/forked-extensions

In case you're too lazy to open these links (because you're too lazy to write your own code):

Forked project must respect copyright law:

- The original copyright holder must be acknowledged in the code files.
- The XML installer file must include a comment on the original extension name. 
- It's considered good practice to provide a link to the original extension URL.

**Comment by stutteringp0et** [comment]
You may think this is funny, but you will never be able to escape the reputation you're building right now.

**Comment by alebak** [comment]
@stutteringp0et Ok, you can request that remove the plugin of JED and don't cry.

The way to write a plugin is the same. You did not create or invented something new and no problem, I go to modify the plugin code and I go to add more features.

**Comment by stutteringp0et** [comment]
diff shows that you only changed variable names.  The order of code is IDENTICAL to my extension.  The class method names are identical, the process is identical.  This is copied.  You are a thief.  Github will forever hold proof of this.

**Comment by stutteringp0et** [comment]
I've already reported you to the JED.  My primary purpose here is to have your repository show that you're a thief.  

Mission Accomplished

**Comment by alebak** [comment]
@stutteringp0et You don't contract me or pay me. And I don't live from this solution.

Very good for the report to JED. I hope that you can cry less and sleep more.

**Comment by stutteringp0et** [comment]
This extension is one of around 30 extensions I have in the JED.  My reputation is built on the code that I write.

Now you're trying to build your reputation on code that I WROTE.

If you had followed the rules and indicated WHERE you got the code from and WHO you got the code from (commonly known as attribution) - I wouldn't have any problem with it.

You removed my name from the code, and by doing so violated my copyright.

**Comment by alebak** [comment]
It's seriously? I don't want discuss more for this. Your reputation is the best, you are winner, you are the champion.

Have a nice day champion ;)

**Comment by alebak** [comment]
@stutteringp0et It's seriously? I don't want discuss more for this. Your reputation is the best, you are winner, you are the champion.

Have a nice day champion ;)
